name = "hturnal-worker"
main = "src/index.ts"
compatibility_date = "2025-07-18"

[durable_objects]
bindings = [
  { name = "HTURNAL_DO", class_name = "HturnalDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["HturnalDurableObject"]

[vars]
STORAGE_BACKEND = "memory"

[triggers]
crons = ["*/1 * * * *"]
